### ISSUE TITLE
Set background color of png converted to jpg?

### ISSUE THREAD

**Issue by OscarGodson** [EyalAr/lwip#103]
I'm trying a bunch of things with no luck. Every png I upload with a transparent background ends up with black as the background color. I want it to be white tho. I tried doing things like this for example:

![utils - vim vim 2015-01-25 19-46-50](https://cloud.githubusercontent.com/assets/20615/5895134/f6b651ec-a4ca-11e4-9860-1538b9f4d464.png)

**Comment by EyalAr** [comment]
`lwip` gives you some low-level tools to handle images. Setting the background color of transparent images can be achieved by:

1. Creating a blank canvas with the background color you want.
2. Pasting your original image on top of that canvas.

Something like this should work (not tested):

```Javascript
// create a canvas with the same dimensions as your image:
lwip.create(image.width(), image.height(), 'white', function(err, canvas){
    // paste original image on top of the canvas
    canvas.paste(0, 0, image, function(err, image){
        // now image has a white background...
    });
});
```

**Comment by OscarGodson** [comment]
:+1: that totally worked. Thank you!
