### ISSUE TITLE
Many warnings on build

### ISSUE THREAD

**Issue by nin-jin** [EyalAr/lwip#104]
..\src\decoder\buffer_worker.cpp(47): warning C4267: 'argument' : conversion from 'size_t' to 'uint32_t', possible loss of data [node_modules\lwip\build\lwip_decoder.vcxproj]

node_modules\lwip\node_modules\nan\nan.h(1086): warning C4244: 'argument' : conversion from 'size_t' to 'double', possi ble loss of data (..\src\decoder\buffer_worker.cpp) [node_modules\lwip\build\lwip_decoder.vcxproj]

.node-gyp\0.10.33\deps\v8\include\v8.h(179): warning C4506: no definition for inline function 'v8::Persistent<v8::Object> v8::Persisten t<v8::Object>::New(v8::Handle<v8::Object>)' (..\src\decoder\jpeg_decoder.cpp) [node_modules\lwip\build\lwip_decoder.vcx proj]

and more more more

windows 8.1
python 2.7
visual studio community 2013 update 4

**Comment by EyalAr** [comment]
You can ignore the compiler warnings.
