### ISSUE TITLE
How to obtain the RGBA buffer?

### ISSUE THREAD

**Issue by unbornchikken** [EyalAr/lwip#105]
I can create an image from a raw RGBA buffer. But how can I extract this from the image object? I can access __lwip.buffer(), but this holds channels differently than RGBA.

I'm looking for a module to support node.js buffer based imaging for my upcoming NOOOCL module (https://github.com/unbornchikken/NOOOCL), and lwip could fill this role, but only if I can extract RGBA buffers from loaded images.

**Comment by unbornchikken** [comment]
I've noticed that lwip.open raw format is not RGBA too as I got before. So my question is: how can I open and save raw RGBA buffers by using lwip?

**Comment by EyalAr** [comment]
Getting a raw pixels buffer is not currently supported.
You can use [`getPixel`](https://github.com/EyalAr/lwip#get-pixel) to build it manually by iterating all the pixels in the image.
