### ISSUE TITLE
Ability to extract EXIF data

### ISSUE THREAD

**Issue by swelham** [EyalAr/lwip#110]
I couldn't see anywhere that states that this is already possible.

The project that I am currently working on requires that I resize the images and extract some info from the EXIF (date taken, etc...). It would be great to be able to this all from this module instead of using multiple modules.

**Comment by EyalAr** [comment]
Please see https://github.com/EyalAr/lwip/issues/100#issuecomment-71363633

**Comment by swelham** [comment]
Oopppss sorry, somehow I missed that!
