### ISSUE TITLE
Cannot install lwip/request compiled version

### ISSUE THREAD

**Issue by vimxts** [EyalAr/lwip#114]
I have many problems and I felt I've wasted a day trying to figure out how can I even install this library. One problem solved then another.

What I did:
-

1. Follow your instruction and install node-gyp
2. Error on configuring because can't find `winsock2.h` apparently.
3. Searched on web and install a bunch of other things.
4. Found another github post suggesting Visual Studio 2010, which contradicts to your instructions.
5. Gave up trying and asking you for help.

Please help me get this installed :(

Not that I'm an expert on node.js, but why can't you release a compiled version of the code? I mean, it's still going to work, right?

**Comment by EyalAr** [comment]
For Windows, [LWIP requires VS2013 or higher](https://github.com/EyalAr/lwip#installation). Other than that, [setting up your system depends on node-gyp](https://github.com/TooTallNate/node-gyp#installation).

Regarding installation with precompiled binaries, it is planned for the next version: https://github.com/EyalAr/lwip/issues/83
