### ISSUE TITLE
0.0.6 not happy in osx 10.10

### ISSUE THREAD

**Issue by corbanb** [EyalAr/lwip#115]
tried to upgrade and not all I get is this. 

node(97379,0x7fff7db2a300) malloc: *** error for object 0x104c00ad0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug

**Comment by EyalAr** [comment]
[Which version of node?](https://github.com/EyalAr/lwip/blob/master/CONTRIBUTING.md#report-bugs)

**Comment by EyalAr** [comment]
Closing until further response.
