### ISSUE TITLE
Get raw pixel buffer?

### ISSUE THREAD

**Issue by OKNoah** [EyalAr/lwip#118]
Hi, currently my code looks like:

	request.get( { url: imageUrl, encoding: 'binary'}, function ( err, response, body ) {
			lwip.open( body, 'JPEG', ...
		})

Is this the wrong kind of buffer? How do I get the right kind of buffer from an image URL?

**Comment by EyalAr** [comment]
What is the specific problem you are having?

**Comment by OKNoah** [comment]
I don't recall the error anymore but should the above code work then?
