### ISSUE TITLE
library does not work in node 0.12.0

### ISSUE THREAD

**Issue by mkoryak** [EyalAr/lwip#119]
Hi, not sure how this relates to https://github.com/EyalAr/lwip/issues/28, I use this lib through another lib as  part of my build process, so I am not in the position to fix it using the solution offered there.

The stacktrace is as follows:

```bash
/Users/misha/Work/hn-squire/node_modules/coffee-script/lib/coffee-script/register.js:45
      Module._extensions[extension](this, filename);
                                   ^
Error: Module did not self-register.
  at Error (native)
  at Module.load (/Users/misha/Work/hn-squire/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at /Users/misha/Work/hn-squire/node_modules/css-sprite/node_modules/lwip/lib/Image.js:8:19
  at Object.<anonymous> (/Users/misha/Work/hn-squire/node_modules/css-sprite/node_modules/lwip/lib/Image.js:471:3)
```

**Comment by diaswrd** [comment]
Hey @mkoryak, I had the same problem when switching from node 0.10 to 0.12 (using [n](https://github.com/tj/n) manager) and I fixed it by simply reinstalling the module.

    $ npm uninstall lwip
    $ npm install lwip

It will run the node-gyp rebuild and put everything in place again.
Hope it helps.

**Comment by EyalAr** [comment]
Thanks @diaswrd 
Indeed, when upgrading node version lwip needs to be reinstalled.
