### ISSUE TITLE
Ability to compress images, or pipe to external compression?

### ISSUE THREAD

**Issue by ryanwalters** [EyalAr/lwip#128]
Is it possible to compress images as a batch step? If not, could we pipe the file through a compression step?

Here is an example:

    var lwip = require('lwip'),
        imagemin = require('image-min');

    lwip.open(file, function (err, image) {
        if (err) throw (err);

        image.batch()
            .cover(width, height)
            .pipe(imagemin({ ext: ext })) // <-- Like this
            .writeFile(file, function (err) {
                if (err) throw (err);

                reply.file(file);
            });
    });

**Comment by EyalAr** [comment]
Seems like imagemin takes a buffer. Use `image.toBuffer` to feed imagemin with the image buffer.
I'm not going to intergrate imagemin into lwip somehow, but I don't see the problem to just use it as a separate tool.
