### ISSUE TITLE
Some crops are 1px wider/taller than canvas

### ISSUE THREAD

**Issue by dotherightthing** [EyalAr/lwip#134]
Some (but not all) of my crops results in a canvas that is 1px wider/taller than the source image.

eg: ![crop-screenshot-kss](https://cloud.githubusercontent.com/assets/638871/7149669/6f7ca07c-e364-11e4-8d4a-997221a07343.png):

* crop is `360 * 466`
* result is `361 * 467`

This could be mitigated somewhat by offering a `fill` option for crops that extend beyond the image canvas, eg a 'white' fill would remove the black line from the right hand edge of my cropped jpeg.

**Comment by EyalAr** [comment]
I'm not sure I understand.

What's the size of the image before cropping?
[Can you give an example image and the code you execute on it?](https://github.com/EyalAr/lwip/blob/master/CONTRIBUTING.md#report-bugs)

**Comment by dotherightthing** [comment]
Thanks for your reply -

[The first screenshot](https://cloud.githubusercontent.com/assets/638871/7806022/d64bc6e4-03cf-11e5-996a-08cbe1b4ece1.png) shows:

* at top left: the source image with a pink box around the banner crop
* at bottom: the source image inspected for native dimensions (1170x4142)
* at right: the LWIP crop from the source image with a 1px line on the right, where I assume the crop has been miscalculated and extended off the edge of the canvas

[The second screenshot](https://cloud.githubusercontent.com/assets/638871/7806021/d64b3ab2-03cf-11e5-8985-d14e9a5b0628.png) shows:

* at top left: the source image with a pink box around the banner crop
* at right: the LWIP crop from the source image with a 1px line on the right, where I assume the crop has been miscalculated and extended off the edge of the canvas
* at bottom: the LWIP crop inspected for native dimensions (1171x296) and the filename of the generated image, showing that the expected size is 1px smaller on both axes (1170x295), and the crop is at x:0px, y:50px

[Here's the function which runs the cropping](https://bitbucket.org/chrometoaster/ct__kss-node-template/src/4221cb0d1f578d37d7a0fa452d8e1da82d1190f7/lwip/app.js?at=master#cl-271) and the versions are:

* [LWIP](https://bitbucket.org/chrometoaster/ct__kss-node-template/src/4221cb0d1f578d37d7a0fa452d8e1da82d1190f7/package.json?at=master#cl-29): `"lwip": "0.0.6"`
* Node: `v0.12.2`
* NPM: `2.7.4`
* OS: `OS X 10.9.5` (Macbook Pro)

Thanks,
Dan

**Comment by EyalAr** [comment]
@dotherightthing 
Note that crop coordinates are inclusive.
I.e. `img.crop(0,0,1,1)` will yield an image of 2X2 pixels, starting from pixel (0,0) up to and including pixel (1,1).

**Comment by dotherightthing** [comment]
Ah, good stuff, thanks @EyalAr - I've adjusted the width and height of my crops by 1 pixel to allow for the 'zero' pixel.
