### ISSUE TITLE
Weird JPEG decoding error

### ISSUE THREAD

**Issue by super-cache-money** [EyalAr/lwip#135]
This module worked like a breeze on my osx system.

I've moved it over to an ubuntu box, and it's erroring. Nothing else has changed, and the rest of the program works perfectly. 

This is literally exactly what I'm trying to do:

    lwip.open(imageBuffer,'jpg', function(err, image){
    }

Here, the image passed to the callback is `null`, and the error is:

`[Error: JPEG decoding error]`

What could be going on here? Any leads would be much appreciated :)

Edit: Was being stupid. sorry.

**Comment by SeanLindnerQ1Media** [comment]
What did you do to resolve the issue? I'm having the exact same problem.

**Comment by cilindrox** [comment]
:+1: having the same issue here

**Comment by super-cache-money** [comment]
I found I was trying to convert a `.png` #ashamed

**Comment by EyalAr** [comment]
You may be trying to decode a file with a 'jpg' extension, which is not actually JPEG.

**Comment by SeanLindnerQ1Media** [comment]
It turned out I was missing a package which was causing the error. It's been a while and I didn't write down exactly what it was.
I believe I had to use sudo apt-get install make and npm install -g node-gyp.
Then rerun npm install lwip and everything worked in my specific case.

**Comment by yayolius** [comment]
Just open the file on a text editor an check if the header says jpeg or png, in my case it was just another formar.

**Comment by anphxyz** [comment]
I got same problem like this, I had use recursion to solve this!
--
myfunction = function(imageBuffer, imgType){
 lwip.open(imageBuffer, imgType, function(err, image){
 if (err != null) { //got jpg decode here
                if (imgType === 'jpg') {
                    myfunction(imageBuffer, 'png');//use recursion to solve this
                } else throw err;
            } else {
                //continue your work here
            }
     }
}
