### ISSUE TITLE
Streaming processing

### ISSUE THREAD

**Issue by tresdin** [EyalAr/lwip#145]
I'm not an expert in image processing. However, I still wonder why doesn't `lwip` implement streaming processing paradigm since it will dramatically reduce the memory usage. Or is there any technical issue with this approach?

**Comment by svzi** [comment]
I totally agree with that. The possibility to work with streams would be a tremendous upgrade! Please think about that.

**Comment by EyalAr** [comment]
@tresdin 

    it will dramatically reduce the memory usage

Why?

**Comment by tresdin** [comment]
@EyalAr Basically, instead of buffering the whole source into memory, data will be sliced into chunks of few KBs for being proccessed. This approach is widely used for uploading/downloading large files.

**Comment by EyalAr** [comment]
It may be true for sending files over the network, but in order to process an image you need the whole of it in memory.

**Comment by EyalAr** [comment]
If you just want it as a convenience API to pipe to/from stream consumers/producers, you can use the image buffer as a basis for a stream.
Something like this: http://stackoverflow.com/questions/16038705/how-to-wrap-a-buffer-as-a-stream2-readable-stream

**Comment by tresdin** [comment]
@EyalAr After googling for **stream image processing**, I found that this idea is possible but it seems to be harder to implement than the traditional approach. Although it's a huge pain to redesign `lwip` processing paradigm, I still think this idea is worth to be considered.

Refferences
http://www.ece.neu.edu/groups/nucar/publications/SAMOS07.pdf
https://www.fer.unizg.hr/_download/repository/JosipKnezovic-Kvalifikacijski.pdf

**Comment by felixfbecker** [comment]
I want to process an image uploaded with PUT, so I have the image as a `req` stream. I understand that streamed processing is not possible without a lot of work, I just want to know how I can convert the stream to a buffer to pass it to lwip. Maybe we could add an example to readme or make `open` also accept a stream for convenience?
