### ISSUE TITLE
Remove image background 

### ISSUE THREAD

**Issue by tinchox5** [EyalAr/lwip#149]

**Comment by EyalAr** [comment]
[Please provide an explanation.](https://github.com/EyalAr/lwip/blob/master/CONTRIBUTING.md#suggest-features--improvements)

I don't understand what do you mean by "remove image background".

**Comment by tinchox5** [comment]
Hi, sorry what I wish is a feature that allow to remove "automatically" the background of the images. Something like this http://www.imagemagick.org/Usage/masking/#bg_remove
