### ISSUE TITLE
lwip.batch().open()... instead of lwip.open().batch()

### ISSUE THREAD

**Issue by Duffycola** [EyalAr/lwip#158]
I have a clean Q promise-based code structure. One thing I noticed when trying to integrate lwip was that the regular callback-based calls would quickly lead to very nested code. The batch() function is a convenient method to chain function calls. However. I then noticed that you first have to open the image, before you can chain the batch up. I think it would be convenient if you could declare a batch object at the root and then have open as part of the batch operation. This way, code could look something like this:

```
lwip.batch().open(buffer, 'jpg').resize(width, height, 'lanczos').toBuffer('jpg', {}, function(err,res){} );
```

instead of

```
lwip.open(buffer, 'jpg', function(err, res) {
   res.batch().resize(width, height, 'lanczos').toBuffer('jpg',{}, function (e, r) {} );
});
```

**Comment by EyalAr** [comment]
`batch` is currently generated from an `Image` object, Which means you need to have the image before creating the batch object.
