### ISSUE TITLE
lwip and promises

### ISSUE THREAD

**Issue by Duffycola** [EyalAr/lwip#159]
What's the best ways to "promisify" lwip calls?
Currently, the only option I see is to bind lwip node-style calls to promises using Q.nfapply().
However, I currently would have to create a promise for every single operation and return it up the chain.
I would rather chain it and see the .batch() method as basically doing the same thing, except it's using node-style functions.
Ideally I would be able to write code like this:

I was hoping to do something like this, using kriskowal's Q library:

q-based-promise
.then(function (imageBuffer) {
  if (options.rescale) {
      var promise = Q.nfcall(lwip.open, imageBuffer, 'jpg').then(function(openedImage){
                       return Q.nfcall( openedImage.batch().resize(options.scaledWidth, options.scaledHeight, 'lanczos').toBuffer, 'jpg', {} );
                    });
      return promise;
   }
  return Q(imageBuffer);
})
.then(function(imageBuffer){
...
});

I basically get
I am able to bind each individual node-style function to Q (such as lwip.open, openedImage.resize, openedImage.toBuffer), but when I use the batch I get the following error:

[TypeError: Object #<Object> has no method 'exec']

See also #158, which is related.

**Comment by pajtai** [comment]
looking at this:

https://github.com/nkt/node-lwip-promise/blob/master/index.js

seems like the way to do it is:

```javascript
var Promise = require('bluebird');
var lwip = Promise.promisifyAll(require('lwip'));

Promise.promisifyAll(require('lwip/lib/Image').prototype);
Promise.promisifyAll(require('lwip/lib/Batch').prototype);

module.exports = lwip;
```
