### ISSUE TITLE
Low performance in image manipulation

### ISSUE THREAD

**Issue by rodrigouroz** [EyalAr/lwip#160]
First of all I'm not sure I'm not doing something wrong or trying to accomplish something this library is not suited for.

I'm trying to manipulate an image at the byte level (stenography) and I'm getting a very slow performance.

This is what I'm doing:

```javascript
lwip = require('lwip')

// obtain an image object:
lwip.open('image.jpg', 
  function(err, image){
    if (!err) {

      var width = image.width();
      var height = image.height();
      var x;
      var y;
      var pixel;
      
      lwip.create(width, height, function (err, newImage) {

        var batch = newImage.batch();

        for (var i = 0; i < width * height; i++) {
          x = i % width;
          y = Math.floor(i / width);
          pixel = image.getPixel(x, y);
          // perform some manipulation
          batch.setPixel(x, y, pixel);
        }

        batch.writeFile('test.jpg', function (err) {
          if (err) return console.log(err);
        });

      });
        
    }
  }
);
```

Is there a better way of doing this?

This takes ~2.5 minutes with a 2000x1500 pixels JPEG file in an 1,8 GHz Intel Core i5

**Comment by EyalAr** [comment]
You have 3,000,000 operations which need to be done sequentially. Unfortunately I don't see a way to improve this on the JS side.
