### ISSUE TITLE
PNG metadata

### ISSUE THREAD

**Issue by joannajw** [EyalAr/lwip#164]
I'm using lwip as part of a project at LinkedIn with @chriseppstein, which involves generating custom PNG images from other images. Since this is computationally expensive, we are currently saving certain information to check if our PNGs need to be regenerated, such as the modification times of the source images. We would ideally like to save this information in the PNG metadata, perhaps in a a tEXt data chunk, and were considering writing this feature for lwip. Is this a feature you would consider accepting, and if so do you have any opinions on how that should be implemented?

**Comment by EyalAr** [comment]
> Is this a feature you would consider accepting

Absolutely.

> how that should be implemented?

I would start by learning how the PNG format defines storing text data in the file. Then this would have to be supported by the [decoder](https://github.com/EyalAr/lwip/blob/master/src/decoder/png_decoder.cpp) and the [encoder](https://github.com/EyalAr/lwip/blob/master/src/encoder/png_worker.cpp).  
Additionally, the lwip [Image type](https://github.com/EyalAr/lwip/blob/master/lib/Image.js) would have to support storing and accessing this data. I.e., passing initial data in the constructor, and providing a 'getMetadata' and 'setMetadata' methods on the prototype.  
When an image is decoded from PNG, its metadata would be passed into the Image constructor. When an image is encoded into PNG, the metadata on the Image object would be passed to the encoder.  
For all other formats (JPEG and GIF) it will be ignored for now.
