### ISSUE TITLE
How to draw a sqare?

### ISSUE THREAD

**Issue by IonicaBizau** [EyalAr/lwip#166]
This is a great library!

How can I create an image containing a square and maybe some text? Are there any functions to do that?

**Comment by EyalAr** [comment]
Currently there are not drawing methods.
You can use [`image.setPixel`](https://github.com/EyalAr/lwip#set-pixel) to draw manually.

**Comment by IonicaBizau** [comment]
@EyalAr Would it make sense to keep this library low level and libraries that offer features like these (text, drawings) will be built on top of `lwip`?

**Comment by EyalAr** [comment]
Drawing methods can definitely be implemented as a separate module.

However, using `setPixel` to set each pixel individually may prove to be quite slow for large drawings.
In order to make drawing of primitive shapes faster, this would have to be implemented in the [native part](https://github.com/EyalAr/lwip/tree/master/src/image).

**Comment by IonicaBizau** [comment]
Ouch, I'm not a c++ hacker... :smile: What I love a lot here is that this module doesn't depends on other binaries (e.g. `graphicsmagick`).

Do you have any idea where should I start to get the pixels of a text? For example, if I want to display *Hello World* with font-size *10px* and font *Arial*, how do I know what the pixels are?

**Comment by EyalAr** [comment]
That's the big question :-)

The most straightforward way I can think of right now is:

1. Make (in advance) an image for each character (an image for 'a', 'A', 'b', 'B', etc.) with transparent background (basically a map of black and transparent pixels).
2. Paste the character images corresponding to the text you want to write on top of your target image.
3. Scale the character images before pasting them to achieve the desired "font size", if needed.

Caveats of this method:

1. Need a different set of character images for each font.
2. Scaling the character images may reduce their quality and sharpness (probably need to use "nearest neighbour" interpolation).

I'm sure it's possible to think of smarter ways to do this.

**Comment by IonicaBizau** [comment]
Thanks! :smile:

**Comment by EyalAr** [comment]
Please let me know if you come up with something :)
(Either as a separate module or as a PR for lwip)

**Comment by IonicaBizau** [comment]
Actually, I see there is an issue about that /cc #54
