### ISSUE TITLE
Black borders after resize

### ISSUE THREAD

**Issue by katspaugh** [EyalAr/lwip#168]
Hi!

I'm using `lwip` to resize images from 900x900 to 300x300. My code looks like this:

```javascript
    lwip.open(inputImageBuffer, imageType, (err, image) => {
      return image.resize(300, 300, 'lanczos', (err, img) => {
        img.toBuffer(imageType, (err, buf) => defer.resolve(buf))
      })
    })
```

After the resize, my small images have a black border at the right and botom sides. Here's one of the resized images:

![resized](https://www.mycs.io/assets/c507a5f79b46ce8f3f2a10eb7d5065d352903d98_square.jpg)

[The original image](https://www.mycs.io/assets/c507a5f79b46ce8f3f2a10eb7d5065d352903d98.jpg) of course doesn't have these borders.

I tried working this around by using `scale` instead of `resize` (same result) and resizing to 301x301 and then cropping (also no effect).

Am I doing something wrong? Is there a way to not have these black borders?

**Comment by katspaugh** [comment]
I also tried other interpolation methods ("nearest-neighbor", "moving-average", "linear", "grid" and "cubic") to no avail.

**Comment by ivan-kleshnin** [comment]
@katspaugh I don't see black borders in the examples you posted. Maybe it's browser CSS ^_^?

**Comment by katspaugh** [comment]
This is super weird, I don't see the border now :astonished: 
Probably a bug in the browser indeed.
Thanks!
