### ISSUE TITLE
Build breaks on Windows 8

### ISSUE THREAD

**Issue by laggingreflex** [EyalAr/lwip#173]
Trying to install but build always breaks. Windows 8.1. I've tried using both node v0.12 and iojs v2.3. 

[installation log for node v0.12](http://pastebin.com/0SzxRyH3)
[npm-debug.log](http://pastebin.com/PZp1asxn)

[installation log for iojs v2.3](http://pastebin.com/7B32czRR)
[npm-debug.log](http://pastebin.com/YgFUnHNL)

I have MS Visual Studio 2013 Express installed as recommended on [node-gyp#installation] page, which is working fine, and builds other modules that require it, ex. [zombie]. 

[node-gyp#installation]: http://github.com/TooTallNate/node-gyp#installation
[zombie]: https://github.com/assaf/zombie

**Comment by Fishbowler** [comment]
I hit problems too, as have many Win 8.1 users using node-gyp.
I got through it with  the GYP_MSVS_VERSION environment variable, thanks to 
https://github.com/atom/atom/issues/2435#issuecomment-51180870

**Comment by laggingreflex** [comment]
I had to reinstall visual studio. After that it worked.
