### ISSUE TITLE
Building on Win 7 x64: node-gyp and Visual Studio fail "unresolved externals"

### ISSUE THREAD

**Issue by 26medias** [EyalAr/lwip#174]
Hi,

I'm trying to build on Win 7 x64.
I have Visual Studio 2015 installed, as well as all its requirements (Python 2.7, ....)

I tried to build using "npm install", node-gyp and manually using Visual Studio, but always get the same issues.

Here are the fatal errors when building using Visual Studio:
http://i.imgur.com/Na6pPfF.png

Here is the output of node-gyp:
http://i.imgur.com/kDv3Ere.png
http://i.imgur.com/Ro5aP5b.png (last few lines of the console)

When building in Visual Studio, I had to change the config from debug (default) to release, else I was getting this:
http://i.imgur.com/6JR9qlf.png
Looks like the latest node-gyp doesn't support debug by default (the /Debug directory is missing). Node-gyp was re-installed using "npm install -g node-gyp" prior to the build.

Do you have any idea what is going on?

Thanks.

**Comment by iangilman** [comment]
I too am having trouble building on Windows! Win 8.1 x64, VS Community 2015. I've got Python but now it's complaining it can't find CL.exe (which neither can I on my hard drive...supposedly it's part of VS Community?).

**Comment by cedon** [comment]
If you installed VS 2015, the C/C++ tools are not installed by default so you'll have to add them. But unfortunately it still will not build under Windows if you're using Node 4.

**Comment by EyalAr** [comment]
#182 should solve this.
