### ISSUE TITLE
PNG conversion issue

### ISSUE THREAD

**Issue by shantanu77** [EyalAr/lwip#181]
the lib is failing everytime to run any operation on png image. A converted image always end up junked.

original [PNG]
![image](https://cloud.githubusercontent.com/assets/12495122/9843342/ce1a3b0a-5ad6-11e5-99dc-75c3ea9ed253.png)

converted [PNG]
![image](https://cloud.githubusercontent.com/assets/12495122/9843442/d1fdb034-5ad7-11e5-86e7-091d9e6b6025.png)

code

	var  lwipobj = require('lwip');	
	lwipobj.open(base_file_main_masked_png,function(err,baseimgobj){
		baseimgobj.batch().resize(300).writeFile(base_file_main+fileExt, function (err)
		{
			if (err) 
				sails.log.debug("ERROR CREATING "+base_file_main+fileExt, err);
			else 
				sails.log.debug("CREATED "+base_file_main+fileExt);
			callback(null);
		});
	});

The above code is called inside an async.each

**Comment by shantanu77** [comment]
No response!!! as yet.
I realize the issue is if the PNG is bigger than some size (512KB??) The library fails completely.

Any solution? work around?

**Comment by r1cebank** [comment]
Maybe wait?

Or you can try fixing it and create a pull request. I believe the author is pretty busy right now, the more critical nodejs 4.0 bug has not fixed yet, give it time.

**Comment by shantanu77** [comment]
Yes thats a good option. Just want to be sure that actually is a issue and I am not doing something wrong.

**Comment by r1cebank** [comment]
Yeah, many stuff is broken. Looks like the author is away.

**Comment by EyalAr** [comment]
@shantanu77, @r1cebank I'll look into it as soon as I can.
In the meantime, if you encode the same image to jpeg what the result?

**Comment by EyalAr** [comment]
@shantanu77 Also please [include more info about your setup](https://github.com/EyalAr/lwip/blob/master/CONTRIBUTING.md#report-bugs).

**Comment by r1cebank** [comment]
No worries, thanks for keeping us updated.

**Comment by shantanu77** [comment]
Welcome Back Eyal! and thank you for responding.

1. there is no issue with async [each] processing the service work like charm. I created 5 different formats (re-sized versions) in parallel all were created fine.


2. the problem exists in PNG->JPG Conversion too
original PNG 
![image](https://cloud.githubusercontent.com/assets/12495122/9927149/a8e0e6e4-5d39-11e5-9e76-677912c4b5a7.png)
[size 350kb]

converted jpg
![image](https://cloud.githubusercontent.com/assets/12495122/9927165/c6271e94-5d39-11e5-80a6-a82c2ac0b2d7.png)
[size 187KB]

3. there is no problem in converting a jpg to other formats.

**Comment by shantanu77** [comment]
ubuntu@test2015:~$ uname -a
Linux test2015.thirstt.com 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux


ubuntu@test2015:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:        14.04
Codename:       trusty

ubuntu@test2015:~$ node --version
v0.12.7



installation data:

../src/lib/gif/quantize.c:132:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (NewColorMapSize < *ColorMapSize) {
                         ^
../src/lib/gif/quantize.c:141:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (i = 0; i < NewColorMapSize; i++) {
                   ^
  SOLINK_MODULE(target) Release/obj.target/lwip_encoder.node
  COPY Release/lwip_encoder.node
  CXX(target) Release/obj.target/lwip_image/src/image/init.o
  CXX(target) Release/obj.target/lwip_image/src/image/image.o
  CXX(target) Release/obj.target/lwip_image/src/image/resize_worker.o
  CXX(target) Release/obj.target/lwip_image/src/image/rotate_worker.o
  CXX(target) Release/obj.target/lwip_image/src/image/blur_worker.o
  CXX(target) Release/obj.target/lwip_image/src/image/crop_worker.o
  CXX(target) Release/obj.target/lwip_image/src/image/mirror_worker.o
  CXX(target) Release/obj.target/lwip_image/src/image/pad_worker.o
  CXX(target) Release/obj.target/lwip_image/src/image/sharpen_worker.o
  CXX(target) Release/obj.target/lwip_image/src/image/hsla_worker.o
  CXX(target) Release/obj.target/lwip_image/src/image/opacify_worker.o
  CXX(target) Release/obj.target/lwip_image/src/image/paste_worker.o
  CXX(target) Release/obj.target/lwip_image/src/image/setpixel_worker.o
  SOLINK_MODULE(target) Release/obj.target/lwip_image.node
  COPY Release/lwip_image.node
make: Leaving directory `/home/ubuntu/www/thirstt/node_modules/lwip/build'
npm WARN unmet dependency /home/ubuntu/www/thirstt/node_modules/sails/node_modules/waterline requires bluebird@'~2.9.25' but will load
npm WARN unmet dependency /home/ubuntu/www/thirstt/node_modules/bluebird,
npm WARN unmet dependency which is version 2.10.0
lwip@0.0.7 node_modules/lwip
├── async@0.9.2
├── nan@1.9.0
└── decree@0.0.6 (lodash-node@2.4.1)

**Comment by shantanu77** [comment]
No response as yet. EylAr. request you to kindly look into it.

**Comment by EyalAr** [comment]
@shantanu77 I can't reproduce the problem...
![res](https://cloud.githubusercontent.com/assets/1146412/10268140/482cbfee-6ab8-11e5-916c-e031898e38e9.png)

Please try again with the latest version of lwip (0.0.8).

**Comment by shantanu77** [comment]
Yes its fixed in 0.0.8 Version. Thank you Very much @EyalAr !

Much appreciated.
