### ISSUE TITLE
Only builds on first install

### ISSUE THREAD

**Issue by F1LT3R** [EyalAr/lwip#183]
The `lwip` library only seems to build the first time I install it on a system. Any further `npm install lwip` fails, and breaks lwip.

**Comment by EyalAr** [comment]
[Please provide more details.](https://github.com/EyalAr/lwip/blob/master/CONTRIBUTING.md#report-bugs)
How does it fail?
What do you see on the console?

**Comment by F1LT3R** [comment]
It seems to be working again. Perhaps it was something wrong with my system.

Perhaps you should close this bug and I'll re-open with the output from my console if I see this come up again.
