### ISSUE TITLE
Not working properly on Node.js 4.0.0

### ISSUE THREAD

**Issue by pandres95** [EyalAr/lwip#184]
Also reporting on https://github.com/nodejs/node/issues/2798 where you can get more information about this issue.

**Comment by cedon** [comment]
I am having this same issue trying to install 'Sprity'

**Comment by antoinepairet** [comment]
The issue comes from the NAN dependency which is currently at `1.8.4`. It should be upgraded to NAN `2.x`. The thread mentioned by @pandres95 provides a lot of info.
I would be glad to help. making the port happen.

**Comment by antoinepairet** [comment]
This is a duplicate of #179

**Comment by EyalAr** [comment]
See #182
