### ISSUE TITLE
MSBUILD : error MSB3411: Could not load the Visual C++ component "VCBuild.exe".

### ISSUE THREAD

**Issue by Parkwookyun** [EyalAr/lwip#190]
I am using

Window 10
node 0.10.13
npm  1.3.2

C:\nawa>npm install lwip
npm http GET https://registry.npmjs.org/lwip
npm http 304 https://registry.npmjs.org/lwip
npm http GET https://registry.npmjs.org/decree/0.0.6
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/decree/0.0.6
npm http GET https://registry.npmjs.org/decree/-/decree-0.0.6.tgz
npm http 200 https://registry.npmjs.org/decree/-/decree-0.0.6.tgz
npm http GET https://registry.npmjs.org/lodash-node
npm http 304 https://registry.npmjs.org/lodash-node

> lwip@0.0.7 install C:\nawa\node_modules\lwip
> node-gyp rebuild

C:\nawa\node_modules\lwip>node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild

MSBUILD : error MSB3411: Could not load the Visual C++ component "VCBuild.exe". If the component is not instal
led, either 1) install the Microsoft Windows SDK for Windows Server 2008 and .NET Framework 3.5, or 2) install
 Microsoft Visual Studio 2008.  [C:\nawa\node_modules\lwip\build\binding.sln]
MSBUILD : error MSB3411: Could not load the Visual C++ component "VCBuild.exe". If the component is not instal
led, either 1) install the Microsoft Windows SDK for Windows Server 2008 and .NET Framework 3.5, or 2) install
 Microsoft Visual Studio 2008.  [C:\nawa\node_modules\lwip\build\binding.sln]
MSBUILD : error MSB3411: Could not load the Visual C++ component "VCBuild.exe". If the component is not instal
led, either 1) install the Microsoft Windows SDK for Windows Server 2008 and .NET Framework 3.5, or 2) install
 Microsoft Visual Studio 2008.  [C:\nawa\node_modules\lwip\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\nawa\node_modules\lwip
gyp ERR! node -v v0.10.13
gyp ERR! node-gyp -v v0.10.2
gyp ERR! not ok
unbuild lwip@0.0.7
npm ERR! weird error 1
npm ERR! not ok code 0

**Comment by EyalAr** [comment]
> error MSB3411: Could not load the Visual C++ component "VCBuild.exe". If the component is not installed, either 1) install the Microsoft Windows SDK for Windows Server 2008 and .NET Framework 3.5, or 2) install Microsoft Visual Studio 2008.

That's part of Visual Studio.

[More info on how to set up your system](https://github.com/nodejs/node-gyp#installation).
