### ISSUE TITLE
Node-Webkit

### ISSUE THREAD

**Issue by xTear** [EyalAr/lwip#192]
Ive build the modul for node-Webkit on a windows vps, the module compiles, but if i require it in the application it fire's an alert with the message: Uncaught Error: No Error PATH/TO/lwip_image.node

build with nw-gyp: nw-gyp --target=0.11.6 --msvs_version=2012

Build on an x64 Windows Server 2008

**Comment by EyalAr** [comment]
[Seems like a node-webkit problem.](https://github.com/nwjs/nw.js/issues/199)
[Make sure you didn't rename nw.exe](https://github.com/nwjs/nw.js/wiki/Build-native-modules-with-nw-gyp).
Also I see you are using VS2012, but to compile LWIP [you need VS2013 or later](https://github.com/EyalAr/lwip#installation).
