### ISSUE TITLE
About GIF thumbnail support

### ISSUE THREAD

**Issue by sarker306** [EyalAr/lwip#198]
I am trying to add support for GIF images in my application. I wish to take user input image, and then make a thumbnail of it.
The process of it is so far:
1) take image, 2) scale it, 3) crop a section
To scale the image I am trying to use image.width() and image.height() property.
But apparently GIF images do not have width and height properties.
So, how is it possible to take the first frame of a GIF image, then scale and crop it , and save as gif using lwip?

**Comment by EyalAr** [comment]
> apparently GIF images do not have width and height properties

Sure they do, or at least they should :)
What have you tried?

**Comment by sarker306** [comment]
Yeah, they should, and they do. After getting your response, I tried again, this time it was okay. I couldn't recreate this scenario, so I guess the features work just fine.
Thanks for your assurance. :+1:
