### ISSUE TITLE
Alpha Channel: Integer 0...100??!!!

### ISSUE THREAD

**Issue by mamekudz** [EyalAr/lwip#199]
What's this? Why not 0...255?

**Comment by EyalAr** [comment]
0% - 100%

**Comment by mamekudz** [comment]
Sure, but the alpha channel value it is an integer, so e.g. (png_worker.cpp):

a = (unsigned char) ((a / 100.0) * 255.0); // range change [0,100] -> [0,255]

will reduces alpha channel resolution to less than an half of the possible resolution.

So, I thing, this library is defected by design :-(
