### ISSUE TITLE
Why encoder and decoder use different pnglibconf.h

### ISSUE THREAD

**Issue by minggo** [EyalAr/lwip#200]
As the title says, i don't know why it is designed like this. 

I want to integrate lwip into electron(not use node module), just compile lwip into Electron.app. Then i want to build lwip as a static lib(include encoder, decoder and image). But i met a problem because encoder and decoder use different pnglibconf.h.

Can i use just one pnglibconf.h and fix compiling error just define macros that needed?
Thanks.

**Comment by minggo** [comment]
Any one knows it?
Thanks.

**Comment by EyalAr** [comment]
The encoder and decoder are compiled separately, and may require different pnglib settings.
You can probably use the same pnglibconf.h for both if it suits your needs.
Just try...

**Comment by minggo** [comment]
@EyalAr 
Thanks. Now i just use the same pnglibconf.h for both by merging the two pnglibconf.h. I am not sure if it has problem, so ask it here.
