### ISSUE TITLE
lwip fails to install gives error MSB8003

### ISSUE THREAD

**Issue by ahgan84** [EyalAr/lwip#212]
Hi guys, I tried to install lwip into my project using "npm install lwip" and it gives the below error:

     MSB8003: Could not find WindowsSDKDir variable from the registry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid version number.
     TRK0005: Failed to locate: "CL.exe"

How to solve this error?

**Comment by EyalAr** [comment]
You need to configure your system. See https://github.com/nodejs/node-gyp#installation
