### ISSUE TITLE
writeFile works but toBuffer is emtpy

### ISSUE THREAD

**Issue by steveg3003** [EyalAr/lwip#216]
I'm not sure if I'm doing something wrong but I can't get toBuffer to work.

I have a file upload via express / multer. I take the png buffer information from multer and upload to AWS S3 and works fine so the buffer appears to be fine. I pass it through this 

    lwip.open(buffer, 'png', function(err, image)
    {
        if(err) // handle error
        var ratio = 1000 / image.width();
        image.batch()
            .scale(ratio)
            .writeFile('temp/image.jpg');
    }

And that works, I get a correctly saved image. but if I switch writeFile to toBuffer

    .toBuffer('jpg', callback...)

and upload that outputted buffer to aws it creates a 0 byte file. I assumed it might be an issue in AWS SDK but when I console log the buffer along with a similar thumbnail resized version I get 2 buffers that are the same (presumably 0 bytes)

I'll try to create a example app in GitHub to demonstrate the issue if there is nothing obviously wrong with the above.

**Comment by EyalAr** [comment]
Hi @steveg3003, if you could upload example code that would be great.

**Comment by steveg3003** [comment]
I've not since been able to replicate, everything is working fine with toBuffer. I'll put it down to a bug else where in my code. I'll update here if I find out more but for now I'll close.
