### ISSUE TITLE
Converting transparent PNG to JPEG (as buffer) adds black background

### ISSUE THREAD

**Issue by igorpavlov** [EyalAr/lwip#233]
It is not possible to specify the background color, or it is not described in the manual.

**Comment by EyalAr** [comment]
Are you referring to PNGs with transparency?

**Comment by EyalAr** [comment]
If yes, you should [paste](https://github.com/EyalAr/lwip#paste) your image on top of a [colored canvas](https://github.com/EyalAr/lwip#create-a-new-image), and then write as JPEG.
