### ISSUE TITLE
work synchronously

### ISSUE THREAD

**Issue by digitalica** [EyalAr/lwip#238]
Would it be possible to work synchronously? I tried to use lwip to process a dir tree with images and other files, no need for async operation. 

Using [deasync](https://github.com/abbr/deasync) didnt work unfortunately (see [issue 49](https://github.com/abbr/deasync/issues/49) there)

**Comment by nvartolomei** [comment]
@digitalica why would you want to make it work sync? Isn't async actually one of the main nodejs and ecosystem strength?

If you want to make your code a little bit more readable you could try [caolan/async](https://github.com/caolan/async). In particular `async.(each|forEachOf|map)` and `async.series`.

**Comment by digitalica** [comment]
@nvartolomei Yes, async is the ecosystem strength, and I like it in many places. But here i'm trying to do batch conversion on a dir tree containing hundreds of files, images and others, that are in part related and dependant on each other. Syncronous code is much more easy to read (at least for me) and debug there. Although it probably could be done async too...

I do use async (already in other places, but now here too) but succeed in working (more) synchronously using Fibers. So my batch conversion is working now using lwip!

Still, I think it would be nice if lwip  could work synchronous too. (Just like fs)

**Comment by felixfbecker** [comment]
@digitalica Use Bluebird's `Promise.promisifyAll` together with `Promise.coroutine` and you can write async code like sync code ;)

**Comment by EyalAr** [comment]
@digitalica lwip is async by design.
As you and others mentioned, there are good abstractions to handle async code (caolan/async, promises, etc.).
