### ISSUE TITLE
Errors installing to amazon elastic beanstalk

### ISSUE THREAD

**Issue by anthonywebb** [EyalAr/lwip#239]
I am running fine on my OSX laptop, but deploying to amazon elastic beanstalk is a no go.  Here are some of the details:

933 info preinstall lwip@0.0.8
934 info linkStuff lwip@0.0.8
935 silly linkStuff lwip@0.0.8 has /tmp/deployment/application/node_modules as its parent node_modules
936 verbose linkBins lwip@0.0.8
937 verbose linkMans lwip@0.0.8
938 verbose rebuildBundles lwip@0.0.8
939 verbose rebuildBundles [ 'async', 'decree', 'nan' ]
940 info install lwip@0.0.8
941 verbose unsafe-perm in lifecycle false
942 info lwip@0.0.8 Failed to exec install script
943 verbose stack Error: lwip@0.0.8 install: `node-gyp rebuild`
943 verbose stack Exit status 1
943 verbose stack     at EventEmitter.<anonymous> (/opt/elasticbeanstalk/node-install/node-v4.2.3-linux-x64/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
943 verbose stack     at emitTwo (events.js:87:13)
943 verbose stack     at EventEmitter.emit (events.js:172:7)
943 verbose stack     at ChildProcess.<anonymous> (/opt/elasticbeanstalk/node-install/node-v4.2.3-linux-x64/lib/node_modules/npm/lib/utils/spawn.js:24:14)
943 verbose stack     at emitTwo (events.js:87:13)
943 verbose stack     at ChildProcess.emit (events.js:172:7)
943 verbose stack     at maybeClose (internal/child_process.js:818:16)
943 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
944 verbose pkgid lwip@0.0.8
945 verbose cwd /tmp/deployment/application
946 error Linux 4.1.13-19.30.amzn1.x86_64
947 error argv "/opt/elasticbeanstalk/node-install/node-v4.2.3-linux-x64/bin/node" "/opt/elasticbeanstalk/node-install/node-v4.2.3-linux-x64/bin/npm" "--production" "rebuild"
948 error node v4.2.3
949 error npm  v2.14.7
950 error code ELIFECYCLE
951 error lwip@0.0.8 install: `node-gyp rebuild`
951 error Exit status 1
952 error Failed at the lwip@0.0.8 install script 'node-gyp rebuild'.
952 error This is most likely a problem with the lwip package,
952 error not with npm itself.
952 error Tell the author that this fails on your system:
952 error     node-gyp rebuild
952 error You can get their info via:
952 error     npm owner ls lwip
952 error There is likely additional logging output above.
953 verbose exit [ 1, true ]

 > lwip@0.0.8 install /tmp/deployment/application/node_modules/lwip
  > node-gyp rebuild
  
  gyp ERR! clean error 
  gyp ERR! stack Error: EACCES: permission denied, rmdir 'build'
  gyp ERR! stack     at Error (native)
  gyp ERR! System Linux 4.1.13-19.30.amzn1.x86_64
  gyp ERR! command "/opt/elasticbeanstalk/node-install/node-v4.2.3-linux-x64/bin/node" "/opt/elasticbeanstalk/node-install/node-v4.2.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bi
n/node-gyp.js" "rebuild"
  gyp ERR! cwd /tmp/deployment/application/node_modules/lwip
  gyp ERR! node -v v4.2.3
  gyp ERR! node-gyp -v v3.0.3
  gyp ERR! not ok 
  
  npm ERR! Linux 4.1.13-19.30.amzn1.x86_64
  npm ERR! argv "/opt/elasticbeanstalk/node-install/node-v4.2.3-linux-x64/bin/node" "/opt/elasticbeanstalk/node-install/node-v4.2.3-linux-x64/bin/npm" "--production" "rebuild"
  npm ERR! node v4.2.3
  npm ERR! npm  v2.14.7
  npm ERR! code ELIFECYCLE
  npm ERR! lwip@0.0.8 install: `node-gyp rebuild`
  npm ERR! Exit status 1
  npm ERR! 
  npm ERR! Failed at the lwip@0.0.8 install script 'node-gyp rebuild'.
  npm ERR! This is most likely a problem with the lwip package,
  npm ERR! not with npm itself.
  npm ERR! Tell the author that this fails on your system:
  npm ERR!     node-gyp rebuild
  npm ERR! You can get their info via:
  npm ERR!     npm owner ls lwip
  npm ERR! There is likely additional logging output above.
  
  npm ERR! Please include the following file with any support request:
  npm ERR!     /tmp/deployment/application/npm-debug.log
  Running npm install:  /opt/elasticbeanstalk/node-install/node-v4.2.3-linux-x64/bin/npm
  Setting npm config jobs to 1
  npm config jobs set to 1
  Running npm with --production flag
  Failed to run npm install. Snapshot logs for more details.

**Comment by coderbyheart** [comment]
I have also trouble building lwip on EBS:

    ../src/lib/png/pngrtran.c:4995:1: fatal error: opening dependency file ./Release/.deps/Release/obj.target/lwip_decoder/src/lib/png/pngrtran.o.d.raw: No such file or directory

Complete log: https://gist.github.com/coderbyheart/fc4e8fd0f903b7e69714d54819b400ef

**Comment by EyalAr** [comment]
Error: EACCES: permission denied, rmdir 'build'

Looks like permissions issue on the machine you're using
