### ISSUE TITLE
I have to NPM rebuild everytime I pull from my team's repo

### ISSUE THREAD

**Issue by jwerardi** [EyalAr/lwip#248]
Hi,

Ever since my team installed lwip into our MEAN app, we have to npm rebuild everytime we pull from our repo. 

When we npm rebuild, the thing that appears the most are the lwip modules being repaired. Is this common? What is exactly going on? Do we have some sort of botched installation? It's not really a big deal, it's just minorly concerning as well as a minor waste of time because it takes ~2 minutes to rebuild everytime we pull.

**Comment by EyalAr** [comment]
@jwerardi,
I'm not sure what you mean by "lwip modules being repaired", but every time you install lwip it will go through the entire installation procedure (including compilation of native code).
