### ISSUE TITLE
Error building in Windows 10

### ISSUE THREAD

**Issue by OussamaRomdhane** [EyalAr/lwip#280]
I had an issue installing lwip for Windows 10 x64

[![Untitled.png](https://s13.postimg.org/ubs5l0a5z/Untitled.png)](https://postimg.org/image/l3zx4b33n/)

[npm-debug.log](https://ufile.io/2976)

**Comment by Yording** [comment]
i have same error, Apparently the package is discontinued.

**Comment by Yording** [comment]
@OussamaRomdhane i have same issue, Apparently the package is discontinued. 
i try to `npm  i --force lwip`

**Comment by navcas** [comment]
on windows 10 execute
`npm install --global windows-build-tools`
then  `npm install --global node-gyp`
and last `npm install lwip`

info from: https://github.com/Microsoft/nodejs-guidelines/blob/master/windows-environment.md#compiling-native-addon-modules

**Comment by OussamaRomdhane** [comment]
Thanks guys for the help.. But I already switched back to Ubuntu :smile:

**Comment by NPCRUS** [comment]
pablis00, your commands doesn't work for me, have the same error

**Comment by milewski** [comment]
@OussamaRomdhane even on ubuntu mine is failing... what is the secret?

**Comment by OussamaRomdhane** [comment]
@Milewski Just make sure you have a c compiler (gcc), make and python 2.7.x . It should work.

Check if you do have them using

`gcc --version`
`python --version` (This must return 2.7.x mine is 2.7.12)
and 
`make --version`

Ubuntu should come with all of them (a bit not sure when it comes to python) installed

**Comment by milewski** [comment]
@OussamaRomdhane i have these as node-canvas recommended

```
apt-get install -y libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++ gcc
```

and  python 2.7, i even did this to ensure npm is using the right python...

```
npm config set python /usr/bin/python2.7
```

but `npm rebuild lwip` still fails....

error

```
npm info lifecycle lwip@0.0.8~install: Failed to exec install script
npm ERR! Linux 4.4.20-moby
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "rebuild" "lwip"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! lwip@0.0.8 install: `node-gyp rebuild`
npm ERR! Exit status 1

```

**Comment by OussamaRomdhane** [comment]
@Milewski I don't know man, maybe it's the node version?
