### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by landau** [EyalAr/lwip#291]
There are many issues and PRs unanswered. I am curious about the viability of this project.

**Comment by factor-irl** [comment]
Whats the issues? Just made a project based off of this today

**Comment by EyalAr** [comment]
Hi, I can't put much time in it myself currently, but PRs / contributions are welcome, and would be happy to add collaborators who'd be interested in maintaining this project.

**Comment by landau** [comment]
Thanks for the response.
