### ISSUE TITLE
Promises Support

### ISSUE THREAD

**Issue by gkaimakas** [EyalAr/lwip#63]
Can you please support promises for the callbacks ?

**Comment by cookch10** [comment]
Without modifying the core library, I've used https://github.com/then/promise successfully to promisify multiple lwip image processing steps.  Would be happy to create a Gist if there's any interest.

**Comment by nkt** [comment]
I've created package that implements this issue: https://github.com/nkt/node-lwip-promise.
It's successfully works in production right now. Thanks!

**Comment by felixfbecker** [comment]
That would indeed be a very nice feature. The future is definitely moving towards promises, as they drive ES7 async/await functions, which you can use today with babel or co. I'm against wrapper modules because they might not be always up-to-date, so promisifyAll for now, but that Async suffix and the boilerplate is annoying.

This module is very callback-hellish. This is an example from http://thejackalofjavascript.com/image-manipulation-node-js/ for a simple image manipulation:
```js
var lwip = require('lwip');
 
var lefty, righty;
 
lwip.open('images/portrait.jpg', function(err, image) {
  var imgWidth = image.width(),
    imgHeight = image.height();
 
  image.crop(0, 0, (imgWidth / 2) - 1, imgHeight - 1, function(err, cropped) {
    lefty = cropped;
    lefty.writeFile('images/processed/portrait_lefty.jpg', function(err) {
      if (err) throw err;
 
      // re-opening the same image, coz the `image` is == `cropped`
      // If we do not get a fresh copy, we will be modifing the cropped image :(
 
      lwip.open('images/portrait.jpg', function(err, image) {
        if (err) throw err;
 
        var imgWidth = image.width(),
          imgHeight = image.height();
 
        image.crop(imgWidth / 2, 0, imgWidth - 1, imgHeight - 1, function(err, cropped) {
          if (err) throw err;
 
          righty = cropped;
 
          righty.writeFile('images/processed/portrait_righty.jpg', function(err) {
            if (err) throw err;
 
            lwip.create(imgWidth, imgHeight, 'white', function(err, newImg) {
              if (err) throw err;
 
              newImg.paste(0, 0, righty, function(err, newImg) {
                if (err) throw err;
 
                newImg.paste(imgWidth / 2, 0, lefty, function(err, newImg) {
                  if (err) throw err;
 
                  newImg.border(18, 'gray', function(err, newImg) {
                    if (err) throw err;
 
                    newImg.writeFile('images/processed/portrait_new.jpg', function(err) {
                      if (err) throw err;
                    }); // write the final output
 
                  }); // add a border - for fun \O/
 
                }); // paste lefty to the right part of the new image 
 
              }); // paste righty to the left part of the new image
 
            }); // create a blank image
 
          }); // write righty to file for reference
 
        }); // righty creation
 
      }); // re-open the same image
 
    }); // write lefty to file for reference
 
  }); // lefty creation
});
```
With promises or async/await that would be so much better.

**Comment by felixfbecker** [comment]
Maybe we can add @raine's working example to readme?

**Comment by RobertHerhold** [comment]
@EyalAr 
I seem to be unable to do any kind of promisification of LWIP due to decree. While using a promisified form of the `open` function, I get this error: 

Error: Unknown arguments configuration,images/myimg.png

Is there any way I can still use promises with LWIP?

**Comment by felixfbecker** [comment]
@RobertHerhold this works for me:
```js
const lwip = require('lwip')
Promise.promisifyAll(lwip)
Promise.promisifyAll(require('lwip/lib/Image').prototype)
Promise.promisifyAll(require('lwip/lib/Batch').prototype)
```

**Comment by RobertHerhold** [comment]
@felixfbecker Thanks for the quick response. Turns out my issue was more of a poor understanding of LWIP's API than anything.

**Comment by RobertHerhold** [comment]
@felixfbecker Ran into another issue. I have the following code:

```
return lwip.openAsync(inname)
      .then(image => image.batch().resize(size, size, "nearest-neighbor").toBufferAsync('png'));
```

and I get this error:

```
Unhandled rejection Error: Unknown arguments configuration,200,200,nearest-neighbor
```

**Comment by felixfbecker** [comment]
@RobertHerhold that has nothing to do with promises, please ask this on stackoverflow

**Comment by jpdevries** [comment]
`setPixel` seems to be asynchronous. I want to draw a PNG from scratch and know when it is done. Would be great to be able to use `Promise.all()` for this.
