### ISSUE TITLE
Asynchronous operations

### ISSUE THREAD

**Issue by benkaiser** [EyalAr/lwip#64]
In my first experimentation with lwip I foolishly thought that because of the callbacks I could do something like this:

``` javascript
lwip.open(filename, extension, function(err, image){
    image.resize(200, function(err, image){
       // do stuff
    }
    image.resize(800, function(err, image){
       // do stuff
    }
});
```

and the resizes would happen in parrallel, however instead it throws an error:

```
/<project>/node_modules/lwip/lib/Image.js:22
        else throw Error("Another image operation already in progress");
                   ^
Error: Another image operation already in progress
    at Error (<anonymous>)
    at Image.__lock (/<project>/node_modules/lwip/lib/Image.js:22:20)
    at Image.resize (/<project>/node_modules/lwip/lib/Image.js:65:14)
    at /<project>/modules/routes.js:208:23
    at /<project>/node_modules/lwip/lib/obtain.js:27:25
```

I know this may be a complex issue, and there is no urgency, I can have them work in series. But to have them work asynchronously would be cool.

**Comment by AckerApple** [comment]
It seems you also cannot process two separate images at the same time. We tried lwip on a development server with only one node process running and when we uploaded simultaneous image buffers and handed them to lwip.open(buffer), often the error of multiple images would be thrown but not every single time (only when two were being resized at the same time)... I would assume you could resize multiple images in an async fashion but we are not finding this to be true. We are only resizing an image once upon upload, no cropping, no additional functions... To fix, for us, we implemented a "master" promise that all image upload buffers would have to "chain" onto to be sure no two uploads processed image resizing at the same time (this still allowed us to at least "send" files simultaneously but only resize one-by-one across all requests).

**Comment by mdcsfk** [comment]
@AckerApple, could you share more information about the promise you have written?

**Comment by mdcsfk** [comment]
will this help?
https://github.com/ybogdanov/node-sync

**Comment by AckerApple** [comment]
The code below is untested and is just to illustrate the CONCEPT of a master promise that runs across all requests. The two keys to this, are creating a promise on server start, and THEN chaining onto that promise with each request. WARNING, the code below is untested and was quickly put together to illustrate concepts (our actual code has too much going on to just copy/paste):

```
var lwip = require('lip');
var masterPromise = Promise.all([]);//this creates an already running promise
var uploadMiddleWare = require('molder').single('expectedFileName');//creates req.files

expressApp.post('/upload-route', uploadMiddleWare, function(req,res,next){
  var openPromise = new Promise(function(resolve,reject){
    lwip.open(req.expectedFileName.buffer, 'jpg', resolve);
  })

  var resizeImage = function(image){
    var resizePromise = new Promise(function(resolve,reject){
      image.resize(width, height, callback);
    });

    return resizePromise;
  }

  var onOpenImage = function(image){
    masterPromise = masterPromise.then(resizeImage);//!!!re-set the masterPromise is key to chaining
  }
  openPromise.then(onOpenImage).catch(next);
})
```
