### ISSUE TITLE
how to maintain aspect ratio while image resize

### ISSUE THREAD

**Issue by pitambar** [EyalAr/lwip#85]
i am trying lwip to resize image for thumbnail with formidable, the images are resized as 200*200 but the aspect raio is not maintain, the quality of image reduces, even used the inter provided by you i.e lanczos and other, but not helped.
how to maintain the aspect ratio of a image while resizeing is there a way to do this, please suggest

**Comment by ahmadnabeelbrainplow** [comment]
here is auto resizing height
https://dustinpfister.github.io/2017/04/10/nodejs-jimp/
