### ISSUE TITLE
resize without distorting (crop and pad)

### ISSUE THREAD

**Issue by dmarcelino** [EyalAr/lwip#88]
Hi @EyalAr, I've started using lwip today and so far I'm enjoying it a lot, thanks! My suggestions:
### .resizeCrop()

The main reason I picked up lwip was for generating thumbnails which I think is a common use (e.g. #85). For that it's really useful to be able to resize and crop the image to the desired size. So I would like to suggest a:
`.resizeCrop()` or extending `.resize()` so it receives an options parameter that would allow to specify how to resize, e.g.: default | crop | pad.

Below is how I'm achieving this in my helper method:

``` javascript
  var widthRatio =  width / image.width();
  var heightRatio = height / image.height();
  var ratio = Math.max(widthRatio, heightRatio);

  image
    .batch()
    .scale(ratio)
    .crop(width, height)
    .exec(callback);
```
### .resizePad()

Similar idea to resize and crop but, instead of cropping, padding the image with the desired color. I've also wrote a helper method for this but would be comfortable if lwip had native support. This suggestion may be the same request as Issue #68.

My helper method:

``` javascript
  var padX = 0;
  var padY = 0;
  var ratio;
  var widthRatio =  width / image.width();
  var heightRatio = height / image.height();

  if(widthRatio < heightRatio){
    ratio = widthRatio;
    var heightBeforePad = Math.floor(ratio * image.height());
    padY = (height - heightBeforePad) / 2;
  } else {
    ratio = heightRatio;
    var widthBeforePad = Math.floor(ratio * image.width());
    padX = (width - widthBeforePad) / 2;
  }

  image
    .batch()
    .scale(ratio)
    .pad(Math.ceil(padX), Math.ceil(padY), Math.floor(padX), Math.floor(padY), color)
    .exec(callback);
```
### resizeProportional()

Just like `resizePad()` except it doesn't really pad. It produces an image that fits the desired size without distorting, cropping or padding.

``` javascript
  var widthRatio =  width / image.width();
  var heightRatio = height / image.height();
  var ratio = Math.min(widthRatio, heightRatio);

  image
    .batch()
    .scale(ratio)
    .exec(callback);
```

Using helper methods for these is fine but I think lots of people would like to have support for these straight out from lwip. Anyway, lwip is a great tool, regards.

**Comment by rob2d** [comment]
would be nice to have a proportional resize regardless of the trivialities of it. We programmers live to remove these :)

**Comment by Bug-Reaper** [comment]
Yea came here because I needed proportional re-size. The behavior of contain is non-intuitive (I've never encountered a contain option that pads width + height) in CSS for example contain will shrink the image AND maintain aspect ratio, I believe this is the most common expected behavior.

While scale does work here, it'd be better to either make contain work as a resize-proportional (or add the option for such) and/or add a resize proportional method that maintains aspect ratio given a max width/height.
