### ISSUE TITLE
Error: %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by gkorland** [EyalAr/lwip#98]
I got the following the error:

```javascript
Tue Dec 30 2014 11:06:36 GMT+0000 (Coordinated Universal Time): Unaught exception: Error: %1 is not a valid Win32 application.
D:\home\site\wwwroot\node_modules\lwip\build\Release\lwip_image.node
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at D:\home\site\wwwroot\node_modules\lwip\lib\Image.js:3:22
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\lwip\lib\Image.js:15:3)
```

**Comment by EyalAr** [comment]
@gkorland Please [provide some more context](https://github.com/EyalAr/lwip/blob/master/CONTRIBUTING.md#report-bugs) about the problem.

**Comment by EyalAr** [comment]
My guess is that you compiled the module on one machine and copied it to another machine, but the bitness of the machines does not match (one is 32bit and the other is 64bit).

**Comment by Anubisss** [comment]
Your compiled lib is in x64, but your node is x86 or vice versa.

**Comment by EyalAr** [comment]
Closed until further response from the OP.

**Comment by NicholasJohn16** [comment]
I'm having this issue. I'm using x64 node.js, x64 nw.js and my system is x64. I've been fighting to get it to compile all day and I've run into this issue intermittently.

**Comment by mgatelabs** [comment]
The question should be, how to compile lwip for x86 on a x64 machine, so it can be redistributed with a x86 exe?
